/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoescalonador;

import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Desktop
 */
public class AppHome extends javax.swing.JFrame {

    /**
     * Creates new form AppHome
     */
    public AppHome() {
        initComponents();
        this.roundRobinSelect.setText("Round Robin");
        this.filaPreemptivaQueue.setText("Fila Preemptiva");
        this.jMenu2.setText("Escalonadores");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartPlotting = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        processResultTable = new javax.swing.JTable();
        turnaroundMean = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        turnaroundFinalValue = new javax.swing.JLabel();
        esperaFinalValue = new javax.swing.JLabel();
        processPane = new javax.swing.JFrame();
        tablePane = new javax.swing.JScrollPane();
        processTable = new javax.swing.JTable();
        processPaneAddProcessBtn = new javax.swing.JButton();
        processPaneCancelBtn = new javax.swing.JButton();
        processPaneReadyBtn = new javax.swing.JButton();
        processListLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        priority_input_label = new javax.swing.JLabel();
        processName = new javax.swing.JTextField();
        arriveTime = new javax.swing.JTextField();
        processDuration = new javax.swing.JTextField();
        processPriorityInput = new javax.swing.JTextField();
        removeTableCell = new javax.swing.JButton();
        generate = new javax.swing.JButton();
        add_proccess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alg_name = new javax.swing.JLabel();
        quantum_label = new javax.swing.JLabel();
        quantum_field = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        roundRobinSelect = new javax.swing.JMenuItem();
        filaPreemptivaQueue = new javax.swing.JMenuItem();

        processResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Processo", "Espera", "Turnaround"
            }
        ));
        jScrollPane2.setViewportView(processResultTable);

        turnaroundMean.setText("Média Turnaround:");

        jLabel6.setText("Média Espera:");

        turnaroundFinalValue.setText("NaN");

        esperaFinalValue.setText("NaN");

        javax.swing.GroupLayout chartPlottingLayout = new javax.swing.GroupLayout(chartPlotting.getContentPane());
        chartPlotting.getContentPane().setLayout(chartPlottingLayout);
        chartPlottingLayout.setHorizontalGroup(
            chartPlottingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartPlottingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chartPlottingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chartPlottingLayout.createSequentialGroup()
                        .addGroup(chartPlottingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(turnaroundMean)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(chartPlottingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(turnaroundFinalValue)
                            .addComponent(esperaFinalValue))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chartPlottingLayout.setVerticalGroup(
            chartPlottingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chartPlottingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(chartPlottingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnaroundMean)
                    .addComponent(turnaroundFinalValue))
                .addGap(28, 28, 28)
                .addGroup(chartPlottingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(esperaFinalValue))
                .addContainerGap())
        );

        processPane.setTitle("Processos");
        processPane.setAlwaysOnTop(true);
        processPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        processPane.setPreferredSize(new java.awt.Dimension(250, 250));

        processTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Processo", "Chegada", "Duracao", "Prioridade"
            }
        ));
        processTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                processTableMouseEntered(evt);
            }
        });
        tablePane.setViewportView(processTable);

        processPaneAddProcessBtn.setText("Adicionar");
        processPaneAddProcessBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processPaneAddProcessBtnMouseClicked(evt);
            }
        });

        processPaneCancelBtn.setText("Cancelar");
        processPaneCancelBtn.setMaximumSize(new java.awt.Dimension(52, 32));
        processPaneCancelBtn.setMinimumSize(new java.awt.Dimension(52, 32));
        processPaneCancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processPaneCancelBtnMouseClicked(evt);
            }
        });

        processPaneReadyBtn.setText("OK!");
        processPaneReadyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processPaneReadyBtnMouseClicked(evt);
            }
        });

        processListLabel.setText("Lista de processos:");

        jLabel3.setText("Processo:");

        jLabel4.setText("Chegada:");

        jLabel5.setText("Duracao:");

        priority_input_label.setText("Prioridade:");

        processName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processNameActionPerformed(evt);
            }
        });

        processPriorityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processPriorityInputActionPerformed(evt);
            }
        });

        removeTableCell.setText("Remover");
        removeTableCell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeTableCellMouseClicked(evt);
            }
        });
        removeTableCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTableCellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout processPaneLayout = new javax.swing.GroupLayout(processPane.getContentPane());
        processPane.getContentPane().setLayout(processPaneLayout);
        processPaneLayout.setHorizontalGroup(
            processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processPaneLayout.createSequentialGroup()
                        .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, processPaneLayout.createSequentialGroup()
                                .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(priority_input_label)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(processName)
                                    .addComponent(processDuration)
                                    .addComponent(arriveTime)
                                    .addComponent(processPriorityInput)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, processPaneLayout.createSequentialGroup()
                                .addComponent(processListLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(processPaneAddProcessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(removeTableCell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(processPaneReadyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(processPaneCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        processPaneLayout.setVerticalGroup(
            processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processPaneLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(processListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(processName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(processPaneAddProcessBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(arriveTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeTableCell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(processDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(processPaneReadyBtn))
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(processPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priority_input_label)
                    .addComponent(processPriorityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processPaneCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escalonadores");
        setMaximumSize(new java.awt.Dimension(275, 203));
        setMinimumSize(new java.awt.Dimension(275, 203));

        generate.setText("Gerar");
        generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateMouseClicked(evt);
            }
        });

        add_proccess.setText("Gerenciar processos");
        add_proccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_proccessMouseClicked(evt);
            }
        });
        add_proccess.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                add_proccessComponentResized(evt);
            }
        });
        add_proccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_proccessActionPerformed(evt);
            }
        });

        jLabel1.setText("Algoritmo sel.:");

        alg_name.setText("Round Robin");
        alg_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alg_nameMouseClicked(evt);
            }
        });

        quantum_label.setText("Quantum.:");

        jMenuBar1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jMenuBar1ComponentHidden(evt);
            }
        });

        jMenu2.setText("File");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        roundRobinSelect.setText("Round Robin");
        roundRobinSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundRobinSelectActionPerformed(evt);
            }
        });
        jMenu2.add(roundRobinSelect);

        filaPreemptivaQueue.setText("Fila Preemptiva");
        filaPreemptivaQueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filaPreemptivaQueueMouseClicked(evt);
            }
        });
        filaPreemptivaQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filaPreemptivaQueueActionPerformed(evt);
            }
        });
        jMenu2.add(filaPreemptivaQueue);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(add_proccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantum_label)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alg_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantum_field))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(alg_name))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantum_label)
                    .addComponent(quantum_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_proccess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundRobinSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundRobinSelectActionPerformed
        this.alg_name.setText("Round Robin");
        this.quantum_field.setVisible(true);
        this.quantum_label.setVisible(true);
    }//GEN-LAST:event_roundRobinSelectActionPerformed

    private void filaPreemptivaQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filaPreemptivaQueueActionPerformed
        this.alg_name.setText("Fila Preemptiva");
        this.priority_input_label.setVisible(false);
        this.processPriorityInput.setVisible(false);
        this.quantum_field.setVisible(false);
        this.quantum_label.setVisible(false);
    }//GEN-LAST:event_filaPreemptivaQueueActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
       
    }//GEN-LAST:event_jMenu2MouseClicked

    private void add_proccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_proccessActionPerformed

    }//GEN-LAST:event_add_proccessActionPerformed

    private void add_proccessComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_add_proccessComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_add_proccessComponentResized

    private void add_proccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_proccessMouseClicked
        this.processPane.setSize(400,400);
        this.processPane.setVisible(true);
        this.processPane.setResizable(false);
       
    }//GEN-LAST:event_add_proccessMouseClicked

    private void jMenuBar1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1ComponentHidden

    private void alg_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alg_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_alg_nameMouseClicked

    private void filaPreemptivaQueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filaPreemptivaQueueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_filaPreemptivaQueueMouseClicked

    private void processPriorityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processPriorityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processPriorityInputActionPerformed

    private void processNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processNameActionPerformed

    private void processPaneReadyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processPaneReadyBtnMouseClicked
        this.processPane.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_processPaneReadyBtnMouseClicked

    private void processPaneCancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processPaneCancelBtnMouseClicked
        this.processPane.setVisible(false);
    }//GEN-LAST:event_processPaneCancelBtnMouseClicked

    private void processPaneAddProcessBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processPaneAddProcessBtnMouseClicked
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)this.processTable.getModel();
        
        
        
        try {
            int arrive = Integer.parseInt(this.arriveTime.getText());
            int processDur = Integer.parseInt(this.processDuration.getText());
            int priority = Integer.parseInt(this.processPriorityInput.getText());
	    
            if(arrive >= 0 && processDur >= 0 && priority >= 0){
                tableModel.addRow(new Object[]{this.processName.getText(),arrive, processDur,priority});
            }else{
                JOptionPane.showMessageDialog(null, "Algum valor digitado está incorreto, coloque apenas valores positivos!", "Erro ao adicionar", JOptionPane.ERROR_MESSAGE);
            }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, "Coloque apenas números inteiros para processos, duração e prioridade.", "Erro de caracteres",  JOptionPane.ERROR_MESSAGE);
	}
        
        
        
        
    }//GEN-LAST:event_processPaneAddProcessBtnMouseClicked

    private void processTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_processTableMouseEntered

    private void processTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processTableMouseClicked

        //                .addRow(new Object[]{"blah, "blah", "blah"});
    }//GEN-LAST:event_processTableMouseClicked

    private void removeTableCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTableCellActionPerformed
    }//GEN-LAST:event_removeTableCellActionPerformed

    private void removeTableCellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeTableCellMouseClicked
        int i = this.processTable.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel)this.processTable.getModel();
        if(i>=0){
            tableModel.removeRow(i);
        }else{
            JOptionPane.showMessageDialog(null, "Nao foi possivel deletar esta merda.");
        }
    }//GEN-LAST:event_removeTableCellMouseClicked

    private void generateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseClicked
        Chart ganttChart = new Chart("Gantt Chart");
        this.chartPlotting.setSize(500, 250);
        this.chartPlotting.setVisible(true);
        ganttChart.callPlot();
    }//GEN-LAST:event_generateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_proccess;
    private javax.swing.JLabel alg_name;
    private javax.swing.JTextField arriveTime;
    private javax.swing.JFrame chartPlotting;
    private javax.swing.JLabel esperaFinalValue;
    private javax.swing.JMenuItem filaPreemptivaQueue;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel priority_input_label;
    private javax.swing.JTextField processDuration;
    private javax.swing.JLabel processListLabel;
    private javax.swing.JTextField processName;
    private javax.swing.JFrame processPane;
    private javax.swing.JButton processPaneAddProcessBtn;
    private javax.swing.JButton processPaneCancelBtn;
    private javax.swing.JButton processPaneReadyBtn;
    private javax.swing.JTextField processPriorityInput;
    private javax.swing.JTable processResultTable;
    private javax.swing.JTable processTable;
    private javax.swing.JTextField quantum_field;
    private javax.swing.JLabel quantum_label;
    private javax.swing.JButton removeTableCell;
    private javax.swing.JMenuItem roundRobinSelect;
    private javax.swing.JScrollPane tablePane;
    private javax.swing.JLabel turnaroundFinalValue;
    private javax.swing.JLabel turnaroundMean;
    // End of variables declaration//GEN-END:variables
}
